export const MOVES_BY_POKEMON = {

    tyranitar: [
        "Aerial Ace",
        "Ancient Power",
        "Assurance",
        "Avalanche",
        "Bite",
        "Blizzard",
        "Body Press",
        "Body Slam",
        "Breaking Swipe",
        "Brick Break",
        "Bulldoze",
        "Crunch",
        "Curse",
        "Dark Pulse",
        "Dig",
        "Double-Edge",
        "Dragon Claw",
        "Dragon Dance",
        "Dragon Pulse",
        "Dragon Tail",
        "Earth Power",
        "Earthquake",
        "Endure",
        "Facade",
        "Fire Blast",
        "Fire Fang",
        "Fire Punch",
        "Flamethrower",
        "Fling",
        "Focus Blast",
        "Focus Energy",
        "Focus Punch",
        "Foul Play",
        "Giga Impact",
        "Hard Press",
        "Heavy Slam",
        "Helping Hand",
        "High Horsepower",
        "Hydro Pump",
        "Hyper Beam",
        "Ice Beam",
        "Ice Fang",
        "Ice Punch",
        "Icy Wind",
        "Iron Defense",
        "Iron Head",
        "Knock Off",
        "Lash Out",
        "Leer",
        "Low Kick",
        "Muddy Water",
        "Mud Shot",
        "Mud-Slap",
        "Outrage",
        "Payback",
        "Power Gem",
        "Protect",
        "Rain Dance",
        "Rest",
        "Roar",
        "Rock Blast",
        "Rock Slide",
        "Rock Throw",
        "Rock Tomb",
        "Sandstorm",
        "Sand Tomb",
        "Scary Face",
        "Screech",
        "Shadow Claw",
        "Sleep Talk",
        "Smack Down",
        "Snarl",
        "Spite",
        "Stealth Rock",
        "Stomp",
        "Stomping Tantrum",
        "Stone Edge",
        "Substitute",
        "Sunny Day",
        "Surf",
        "Tackle",
        "Take Down",
        "Taunt",
        "Tera Blast",
        "Thrash",
        "Thunder",
        "Thunderbolt",
        "Thunder Fang",
        "Thunder Punch",
        "Thunder Wave"
    ],

    garchomp: [
        "Aerial Ace",
        "Bite",
        "Body Slam",
        "Breaking Swipe",
        "Brick Break",
        "Bulldoze",
        "Crunch",
        "Dig",
        "Double-Edge",
        "Draco Meteor",
        "Dragon Breath",
        "Dragon Cheer",
        "Dragon Claw",
        "Dragon Pulse",
        "Dragon Rush",
        "Dragon Tail",
        "Earth Power",
        "Earthquake",
        "Endure",
        "Facade",
        "False Swipe",
        "Fire Blast",
        "Fire Fang",
        "Flamethrower",
        "Fling",
        "Giga Impact",
        "Helping Hand",
        "Hyper Beam",
        "Iron Head",
        "Liquidation",
        "Metal Claw",
        "Mud Shot",
        "Outrage",
        "Poison Jab",
        "Power Gem",
        "Protect",
        "Rain Dance",
        "Rest",
        "Rock Slide",
        "Rock Tomb",
        "Sand Attack",
        "Sandstorm",
        "Sand Tomb",
        "Scale Shot",
        "Scary Face",
        "Scorching Sands",
        "Shadow Claw",
        "Slash",
        "Sleep Talk",
        "Spikes",
        "Stealth Rock",
        "Stomping Tantrum",
        "Stone Edge",
        "Substitute",
        "Sunny Day",
        "Surf",
        "Swift",
        "Swords Dance",
        "Tackle",
        "Take Down",
        "Tera Blast",
        "Thrash",
        "Thunder Fang",
        "Twister"
    ],

    charizard: [
        "Acrobatics",
        "Aerial Ace",
        "Air Cutter",
        "Air Slash",
        "Ancient Power",
        "Belly Drum",
        "Bite",
        "Blast Burn",
        "Body Slam",
        "Breaking Swipe",
        "Brick Break",
        "Bulldoze",
        "Counter",
        "Crunch",
        "Dig",
        "Double-Edge",
        "Dragon Breath",
        "Dragon Cheer",
        "Dragon Claw",
        "Dragon Dance",
        "Dragon Pulse",
        "Dragon Rush",
        "Dragon Tail",
        "Earthquake",
        "Ember",
        "Endure",
        "Facade",
        "False Swipe",
        "Fire Blast",
        "Fire Fang",
        "Fire Pledge",
        "Fire Punch",
        "Fire Spin",
        "Flame Charge",
        "Flamethrower",
        "Flare Blitz",
        "Fling",
        "Fly",
        "Focus Blast",
        "Focus Punch",
        "Giga Impact",
        "Growl",
        "Heat Crash",
        "Heat Wave",
        "Helping Hand",
        "Hurricane",
        "Hyper Beam",
        "Inferno",
        "Iron Tail",
        "Metal Claw",
        "Outrage",
        "Overheat",
        "Protect",
        "Rest",
        "Roar",
        "Rock Slide",
        "Rock Tomb",
        "Sandstorm",
        "Scary Face",
        "Scorching Sands",
        "Scratch",
        "Shadow Claw",
        "Slash",
        "Sleep Talk",
        "Smokescreen",
        "Solar Beam",
        "Substitute",
        "Sunny Day",
        "Swift",
        "Swords Dance",
        "Take Down",
        "Temper Flare",
        "Tera Blast",
        "Thunder Punch",
        "Weather Ball",
        "Will-O-Wisp"
    ],

    lucario: [
        "Aerial Ace",
        "Agility",
        "Aura Sphere",
        "Bite",
        "Body Slam",
        "Bone Rush",
        "Brick Break",
        "Bulk Up",
        "Bulldoze",
        "Bullet Punch",
        "Calm Mind",
        "Circle Throw",
        "Close Combat",
        "Coaching",
        "Copycat",
        "Counter",
        "Cross Chop",
        "Crunch",
        "Dark Pulse",
        "Detect",
        "Dig",
        "Dragon Pulse",
        "Drain Punch",
        "Earthquake",
        "Endure",
        "Extreme Speed",
        "Facade",
        "Feint",
        "Final Gambit",
        "Flash Cannon",
        "Fling",
        "Focus Blast",
        "Focus Punch",
        "Force Palm",
        "Giga Impact",
        "Heal Pulse",
        "Helping Hand",
        "High Jump Kick",
        "Howl",
        "Hyper Beam",
        "Ice Punch",
        "Iron Defense",
        "Life Dew",
        "Low Kick",
        "Low Sweep",
        "Metal Claw",
        "Metal Sound",
        "Meteor Mash",
        "Metronome",
        "Nasty Plot",
        "Poison Jab",
        "Protect",
        "Psychic",
        "Psych Up",
        "Quick Attack",
        "Quick Guard",
        "Rain Dance",
        "Rest",
        "Reversal",
        "Roar",
        "Rock Slide",
        "Rock Smash",
        "Rock Tomb",
        "Scary Face",
        "Screech",
        "Shadow Ball",
        "Shadow Claw",
        "Sleep Talk",
        "Steel Beam",
        "Stone Edge",
        "Substitute",
        "Sunny Day",
        "Swift",
        "Swords Dance",
        "Take Down",
        "Tera Blast",
        "Thunder Punch",
        "Trailblaze",
        "Upper Hand",
        "Vacuum Wave",
        "Water Pulse",
        "Work Up",
        "Zen Headbutt"
    ],
};

